# Generated by Django 4.1.7 on 2023-04-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Techniciens',
            fields=[
                ('id_tech', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('prenom', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id_tache', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('titre', models.CharField(blank=True, max_length=50, null=True)),
                ('num_certif', models.DecimalField(decimal_places=0, max_digits=9, null=True)),
                ('sn', models.CharField(max_length=50, null=True)),
                ('pn', models.CharField(max_length=50, null=True)),
                ('lieu', models.CharField(max_length=8, null=True)),
                ('type', models.CharField(max_length=5, null=True)),
                ('statut', models.CharField(max_length=8, null=True)),
                ('commentaire', models.CharField(blank=True, max_length=300, null=True)),
                ('nom_client', models.CharField(blank=True, max_length=50, null=True)),
                ('techniciens', models.ManyToManyField(to='myapp.techniciens')),
            ],
            options={
                'db_table': 'tache',
            },
        ),
    ]
