# Generated by Django 4.1.7 on 2023-04-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tache',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
