# Generated by Django 4.1.7 on 2023-04-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_techniciens_abscence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techniciens',
            name='abscence',
        ),
        migrations.AddField(
            model_name='abscence',
            name='techniciens',
            field=models.ManyToManyField(to='myapp.techniciens'),
        ),
        migrations.AlterField(
            model_name='abscence',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abscence',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tache',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tache',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
