# Generated by Django 4.1.7 on 2023-04-18 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_techniciens_abscence_abscence_techniciens_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Abscence',
            new_name='Absence',
        ),
    ]
