# Generated by Django 4.1.7 on 2023-04-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_abscence_absence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='titre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
