# Generated by Django 4.1.7 on 2023-04-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_tache_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='id_tache',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
