# Generated by Django 4.1.7 on 2023-04-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_tache_num_certif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='id_tache',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tache',
            name='num_certif',
            field=models.IntegerField(null=True),
        ),
    ]
