# Generated by Django 4.1.7 on 2023-04-25 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_tache_id_tache_alter_tache_num_certif'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tache',
            old_name='id_tache',
            new_name='notification',
        ),
        migrations.RemoveField(
            model_name='tache',
            name='num_certif',
        ),
    ]
