# Generated by Django 4.1.7 on 2023-04-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_id_tache_tache_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='motif',
            field=models.CharField(blank=True, default='Motif non soumis', max_length=50, null=True),
        ),
    ]
