# Generated by Django 4.1.7 on 2023-04-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_absence_motif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='motif',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
